spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # Tự động tạo route cho các microservices đã đăng ký với Eureka, là các default routes trong /actuator/gateway/routes
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              # ko tự tạo routes nữa mà tự define bằng RouteLocatorBuilder
              enabled: false
              # gateway tự convert về lowercase
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
    bus:
      enabled: false
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

  security:
    oauth2:
      resourceserver:
        jwt:
          # lấy public key từ keycloak về để xác thực jwt
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # expose endpoint: /actuator/gateway/routes
  endpoint:
    gateway:
      access: unrestricted
  # expose endpoint: /actuator/info
  info:
    env:
      enabled: true
  # bảo micrometer & Prometheus gom tất cả metrics của account service lại
  metrics:
    tags:
      application: ${spring.application.name}

# load từ github repo
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: "http://localhost:8070/eureka/"

# in eureka dashboard
info:
  app:
    name: "gatewayserver"
    description: "Easy Bank Gateway Server Application"
    version: 1.0.0

# bật log cho gatewayserver để log Correlation Id
logging:
  level:
    com:
      easybytes:
        gatewayserver: DEBUG

# truy cập /actuator/circuitbreakers để xem log sau mỗi request
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
