spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  # Cho phép Spring Boot tự động ghép liveness + readiness vào health, nghĩa là chỉ cần gọi /actuator/health là trả về đủ readiness và liveness
  endpoint:
    health:
      probes:
        enabled: true
  # bảo micrometer & Prometheus gom tất cả metrics của account service lại
  metrics:
    tags:
      application: ${spring.application.name}