services:
  network-deploy-service:
    networks:
      - easybank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      # các service đều cần connect với rabbitmq nên override lại trong microservice-base-config này
      # override lại host trong applciation.yml theo tên service trong docker-compose.yml chứ ko để localhost nữa
      SPRING_RABBITMQ_HOST: "rabbitmq"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      # configserver ở đây KHÔNG phải localhost, mà là tên service trong docker network
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root