server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: ''
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  tận dụng file schema.sql
  #  sql:
  #    init:
  #      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # expose endpoint: /actuator/shutdown
  endpoint:
    shutdown:
      access: unrestricted
  # expose endpoint: /actuator/info
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

# in eureka dashboard
info:
  app:
    name: "accounts"
    description: "Easy Bank Accounts Application"
    version: 1.0.0
