server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  tận dụng file schema.sql
#  sql:
#    init:
#      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"