server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password: ''
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  tận dụng file schema.sql
  #  sql:
  #    init:
  #      mode: always
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # dùng circuitbreaker bảo vệ mọi service-to-service call
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    bus:
      enabled: false
    stream:
      bindings:
        # ko có funtion nên đặt binding name bất kì - output - output index
        sendCommunication-out-0:
          # gửi message vào exchange send-communication
          destination: send-communication

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # expose endpoint: /actuator/shutdown
  endpoint:
    shutdown:
      access: unrestricted
    # Cho phép Spring Boot tự động ghép liveness + readiness vào health, nghĩa là chỉ cần gọi /actuator/health là trả về đủ readiness và liveness
    health:
      probes:
        enabled: true
  # expose endpoint: /actuator/info
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  # bảo micrometer & Prometheus gom tất cả metrics của account service lại
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

# in eureka dashboard
info:
  app:
    name: "accounts"
    description: "Easy Bank Accounts Application"
    version: 1.0.0

# bật log cho gatewayserver để log Correlation Id
logging:
  level:
    com:
      easybytes:
        accounts: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

# truy cập /actuator/circuitbreakers để xem log sau mỗi request
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 10000
      failureRateThreshold: 50

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 500
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 2
      # nếu throw exception này thì nó ko retry và chuyển qua hàm fallback luôn
      ignore-exceptions:
        - java.lang.NullPointerException
      # chỉ những exception trong này mới retry còn lại chuyển thẳng sang fallback
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeout-duration: 1000
      limit-refresh-period: 5000
      limit-for-period: 1