services:
  network-deploy-service:
    networks:
      - easybank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      # các service đều cần connect với rabbitmq nên override lại trong microservice-base-config này
      # override lại host trong applciation.yml theo tên service trong docker-compose.yml chứ ko để localhost nữa
      SPRING_RABBITMQ_HOST: "rabbitmq"
      # khi container start, JVM đọc JAVA_TOOL_OPTIONS và load opentelemetry-javaagent.jar, sau đó Agent hook vào Spring Boot tự tạo trace/span
      JAVA_TOOL_OPTIONS: "-javaagent:app/libs/opentelemetry-javaagent-2.22.0.jar"
      # Loki lưu logs, Prometheus lưu metrics, Tempo lưu traces
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      # tắt metrics của Opentelemerty vì đã dùng Micrometer & Prometheus
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # configserver ở đây KHÔNG phải localhost, mà là tên service trong docker network
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      # eurekaserver ko phải là localhost mà là tên service trong docker network
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/